"""baseline schema

Revision ID: ef12c9fe35ca
Revises: 
Create Date: 2026-08-20 19:03:28.254422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef12c9fe35ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_years_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('external_uid', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_external_uid'), ['external_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('client_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_client_user')
    )
    with op.batch_alter_table('client_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_users_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_users_user_id'), ['user_id'], unique=False)

    op.create_table('column_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('sheet_name', sa.String(length=120), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=True),
    sa.Column('first_data_row', sa.Integer(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('column_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_column_mappings_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_mappings_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_mappings_fingerprint'), ['fingerprint'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=30), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tax_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=7), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('gstr1_due_date', sa.Date(), nullable=True),
    sa.Column('gstr3b_due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_tax_period')
    )
    with op.batch_alter_table('tax_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_periods_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_periods_financial_year_id'), ['financial_year_id'], unique=False)

    op.create_table('client_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'employee_id', name='uq_client_assignment')
    )
    with op.batch_alter_table('client_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_assignments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_assignments_employee_id'), ['employee_id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('file_number', sa.String(length=30), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('constitution', sa.String(length=30), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('filing_frequency', sa.String(length=20), nullable=False),
    sa.Column('assigned_employee_id', sa.Integer(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('applicable_services', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_assigned_employee_id'), ['assigned_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_file_number'), ['file_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_entities_gstin'), ['gstin'], unique=True)
        batch_op.create_index(batch_op.f('ix_entities_pan'), ['pan'], unique=False)

    op.create_table('compliance_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('tax_period_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tax_period_id'], ['tax_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'tax_period_id', name='uq_case_entity_period')
    )
    with op.batch_alter_table('compliance_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_cases_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_tax_period_id'), ['tax_period_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_type'), ['target_type'], unique=False)

    op.create_table('return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_employee_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('internal_remarks', sa.Text(), nullable=True),
    sa.Column('review_started_by_user_id', sa.Integer(), nullable=True),
    sa.Column('review_started_at', sa.DateTime(), nullable=True),
    sa.Column('assignment_is_explicit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['review_started_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'return_type', name='uq_case_return_type')
    )
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_items_assigned_employee_id'), ['assigned_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_items_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_items_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_items_return_type'), ['return_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_items_status'), ['status'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('return_item_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('current_version_no', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_return_item_id'), ['return_item_id'], unique=False)

    op.create_table('gstr3b_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('return_item_id', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_item_id')
    )
    with op.batch_alter_table('gstr3b_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gstr3b_payments_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gstr3b_payments_payment_status'), ['payment_status'], unique=False)

    op.create_table('status_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_item_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_transitions_return_item_id'), ['return_item_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_on_behalf_of_client', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_no', name='uq_doc_version')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)

    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('return_item_id', sa.Integer(), nullable=False),
    sa.Column('arn', sa.String(length=30), nullable=True),
    sa.Column('filed_on', sa.Date(), nullable=True),
    sa.Column('portal_reference', sa.String(length=100), nullable=True),
    sa.Column('acknowledgement_document_id', sa.Integer(), nullable=True),
    sa.Column('filed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledgement_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['filed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_item_id')
    )
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filings_arn'), ['arn'], unique=False)
        batch_op.create_index(batch_op.f('ix_filings_case_id'), ['case_id'], unique=False)

    op.create_table('invoice_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('invoice_no_normalized', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_type', sa.String(length=30), nullable=True),
    sa.Column('place_of_supply', sa.String(length=50), nullable=True),
    sa.Column('taxable_value', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('cess', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('itc_available', sa.String(length=5), nullable=True),
    sa.Column('source_row_no', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_records_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_records_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_records_invoice_no_normalized'), ['invoice_no_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_records_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_records_supplier_gstin'), ['supplier_gstin'], unique=False)

    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('return_item_id', sa.Integer(), nullable=False),
    sa.Column('gstr2b_version_id', sa.Integer(), nullable=True),
    sa.Column('pr_version_id', sa.Integer(), nullable=True),
    sa.Column('run_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['gstr2b_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['pr_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], ),
    sa.ForeignKeyConstraint(['run_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_is_superseded'), ['is_superseded'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_return_item_id'), ['return_item_id'], unique=False)

    op.create_table('invoice_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('pr_record_id', sa.Integer(), nullable=True),
    sa.Column('gstr2b_record_id', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.String(length=30), nullable=False),
    sa.Column('diff_flags', sa.JSON(), nullable=True),
    sa.Column('taxable_value_diff', sa.Float(), nullable=False),
    sa.Column('tax_diff', sa.Float(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('assigned_employee_id', sa.Integer(), nullable=True),
    sa.Column('ca_remark', sa.Text(), nullable=True),
    sa.Column('client_response', sa.Text(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['gstr2b_record_id'], ['invoice_records.id'], ),
    sa.ForeignKeyConstraint(['pr_record_id'], ['invoice_records.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_matches_assigned_employee_id'), ['assigned_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_matches_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_matches_match_status'), ['match_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_matches_resolution_status'), ['resolution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_matches_run_id'), ['run_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('return_item_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('invoice_match_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['invoice_match_id'], ['invoice_matches.id'], ),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_invoice_match_id'), ['invoice_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_return_item_id'), ['return_item_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('return_item_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('return_item_id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=True),
    sa.Column('invoice_match_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requires_revision', sa.Boolean(), nullable=False),
    sa.Column('raised_by_user_id', sa.Integer(), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['invoice_match_id'], ['invoice_matches.id'], ),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queries_invoice_match_id'), ['invoice_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queries_return_item_id'), ['return_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queries_status'), ['status'], unique=False)

    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_attachments_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_attachments_message_id'))

    op.drop_table('message_attachments')
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queries_status'))
        batch_op.drop_index(batch_op.f('ix_queries_return_item_id'))
        batch_op.drop_index(batch_op.f('ix_queries_invoice_match_id'))
        batch_op.drop_index(batch_op.f('ix_queries_case_id'))

    op.drop_table('queries')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_return_item_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_invoice_match_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_document_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_client_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_case_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('invoice_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_matches_run_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_matches_resolution_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_matches_match_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_matches_case_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_matches_assigned_employee_id'))

    op.drop_table('invoice_matches')
    with op.batch_alter_table('reconciliation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_return_item_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_is_superseded'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_case_id'))

    op.drop_table('reconciliation_runs')
    with op.batch_alter_table('invoice_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_records_supplier_gstin'))
        batch_op.drop_index(batch_op.f('ix_invoice_records_source'))
        batch_op.drop_index(batch_op.f('ix_invoice_records_invoice_no_normalized'))
        batch_op.drop_index(batch_op.f('ix_invoice_records_document_version_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_records_case_id'))

    op.drop_table('invoice_records')
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filings_case_id'))
        batch_op.drop_index(batch_op.f('ix_filings_arn'))

    op.drop_table('filings')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('status_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_transitions_return_item_id'))

    op.drop_table('status_transitions')
    with op.batch_alter_table('gstr3b_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gstr3b_payments_payment_status'))
        batch_op.drop_index(batch_op.f('ix_gstr3b_payments_case_id'))

    op.drop_table('gstr3b_payments')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_return_item_id'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_type'))
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))

    op.drop_table('documents')
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_items_status'))
        batch_op.drop_index(batch_op.f('ix_return_items_return_type'))
        batch_op.drop_index(batch_op.f('ix_return_items_due_date'))
        batch_op.drop_index(batch_op.f('ix_return_items_case_id'))
        batch_op.drop_index(batch_op.f('ix_return_items_assigned_employee_id'))

    op.drop_table('return_items')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_client_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_case_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('compliance_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_cases_tax_period_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_status'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_entity_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_client_id'))

    op.drop_table('compliance_cases')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_pan'))
        batch_op.drop_index(batch_op.f('ix_entities_gstin'))
        batch_op.drop_index(batch_op.f('ix_entities_file_number'))
        batch_op.drop_index(batch_op.f('ix_entities_client_id'))
        batch_op.drop_index(batch_op.f('ix_entities_assigned_employee_id'))

    op.drop_table('entities')
    with op.batch_alter_table('client_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_assignments_employee_id'))
        batch_op.drop_index(batch_op.f('ix_client_assignments_client_id'))

    op.drop_table('client_assignments')
    with op.batch_alter_table('tax_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_periods_financial_year_id'))
        batch_op.drop_index(batch_op.f('ix_tax_periods_code'))

    op.drop_table('tax_periods')
    op.drop_table('employees')
    with op.batch_alter_table('column_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_column_mappings_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_column_mappings_doc_type'))
        batch_op.drop_index(batch_op.f('ix_column_mappings_client_id'))

    op.drop_table('column_mappings')
    with op.batch_alter_table('client_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_users_client_id'))

    op.drop_table('client_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_external_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('financial_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_years_code'))

    op.drop_table('financial_years')
    op.drop_table('clients')
    # ### end Alembic commands ###
